export const APP_VERSION = '5.0.0-enterprise-foundation';
export const PROJECT_SCHEMA_VERSION = 5;
export const DEFAULT_CONFIG = Object.freeze({
  currency:'USD',locale:'es-VE',workdayHours:8,administrationPct:15,contingencyPct:5,profitPct:10,
  financingPct:0,taxPct:16,clientFactor:1,defaultFcasPct:250,maxPriceAgeDays:90,requireVerifiedPricesForApproval:true
});

export function text(value,max=6000){return String(value??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
export function number(value,fallback=0){const parsed=Number.parseFloat(value);return Number.isFinite(parsed)?parsed:fallback}
export function clamp(value,min,max){return Math.min(max,Math.max(min,number(value,min)))}
export function normalizeUnit(value){
  const raw=text(value,30).toLowerCase().replaceAll('²','2').replaceAll('³','3').replaceAll('^2','2').replaceAll('^3','3');
  const aliases={metro:'m',metros:'m','m.l.':'ml','m.l':'ml',lineal:'ml','metro lineal':'ml','metros lineales':'ml','metro cuadrado':'m2','metros cuadrados':'m2','m²':'m2','metro cubico':'m3','metro cúbico':'m3','metros cubicos':'m3','metros cúbicos':'m3','m³':'m3',unidad:'und',unidades:'und',pieza:'und',piezas:'und',kilogramo:'kg',kilogramos:'kg',kilo:'kg',kilos:'kg',tonelada:'t',toneladas:'t',litro:'l',litros:'l',dia:'día',dias:'día',días:'día',hora:'h',horas:'h',saco:'saco',sacos:'saco',galon:'gal',galón:'gal',galones:'gal'};
  return aliases[raw]||raw||'und';
}
export function isoDate(value=new Date()){const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10)}
export function daysOld(value,now=new Date()){if(!value)return Infinity;const date=new Date(`${value}T00:00:00Z`);return Number.isNaN(date.getTime())?Infinity:Math.max(0,Math.floor((now-date)/86400000))}
export function catalogKey(type,description,unit=''){return `${text(type,20).toLowerCase()}|${text(description,250).toLowerCase()}|${normalizeUnit(unit)}`}
function first(obj,keys,fallback){for(const key of keys)if(obj?.[key]!==undefined&&obj?.[key]!==null)return obj[key];return fallback}
function list(value,max=12){return(Array.isArray(value)?value:[]).map(x=>text(x,700)).filter(Boolean).slice(0,max)}
function priceFields(item,keys,sourceName){return{price:Math.max(0,number(first(item,keys,0))),source:text(first(item,['fuente_precio','fuente','source','price_source'],''),300)||`Estimación ${sourceName} no verificada`,date:isoDate(first(item,['fecha_precio','fecha','date','price_date'],'')),verified:Boolean(first(item,['precio_verificado','verificado','verified'],false))}}

export function normalizeApu(raw,prompt='',sourceName='IA'){
  if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('La IA no devolvió un objeto APU.');
  const warnings=list(first(raw,['advertencias','warnings'],[]),20),omitted=[];
  const materiales=(Array.isArray(first(raw,['materiales','materials'],[]))?first(raw,['materiales','materials'],[]):[]).slice(0,30).map((item,index)=>{
    const cant=number(first(item,['cant','cantidad','quantity','consumo'],0));if(!(cant>0)){omitted.push(`material ${index+1}`);return null}const p=priceFields(item,['precio','precio_unitario','price','unit_price'],sourceName);
    return{id:text(first(item,['id'],''),80)||`mat-${index+1}`,desc:text(first(item,['desc','descripcion','description','material'],''),250)||`Material ${index+1}`,und:normalizeUnit(first(item,['und','unidad','unit'],'und')),cant,precio:p.price,fuente_precio:p.source,fecha_precio:p.date,precio_verificado:p.verified};
  }).filter(Boolean);
  const equipos=(Array.isArray(first(raw,['equipos','equipment','maquinaria'],[]))?first(raw,['equipos','equipment','maquinaria'],[]):[]).slice(0,20).map((item,index)=>{
    const cant=number(first(item,['cant','cantidad','quantity'],0));if(!(cant>0)){omitted.push(`equipo ${index+1}`);return null}const p=priceFields(item,['tarifa','precio','rate','daily_rate'],sourceName);
    return{id:text(first(item,['id'],''),80)||`eq-${index+1}`,desc:text(first(item,['desc','descripcion','description','equipo'],''),250)||`Equipo ${index+1}`,cant,tarifa:p.price,fuente_precio:p.source,fecha_precio:p.date,precio_verificado:p.verified};
  }).filter(Boolean);
  const mo=(Array.isArray(first(raw,['mo','mano_obra','manoObra','labor'],[]))?first(raw,['mo','mano_obra','manoObra','labor'],[]):[]).slice(0,20).map((item,index)=>{
    const cant=number(first(item,['cant','cantidad','quantity'],0));if(!(cant>0)){omitted.push(`cargo ${index+1}`);return null}const p=priceFields(item,['jornal','precio','wage','daily_wage'],sourceName);
    return{id:text(first(item,['id'],''),80)||`mo-${index+1}`,cargo:text(first(item,['cargo','desc','descripcion','role'],''),250)||`Trabajador ${index+1}`,cant,jornal:p.price,fuente_precio:p.source,fecha_precio:p.date,precio_verificado:p.verified};
  }).filter(Boolean);
  if(omitted.length)warnings.push(`Se omitieron recursos con cantidades inválidas: ${omitted.join(', ')}.`);
  const covenin=text(first(raw,['covenin','codigo_covenin','code'],''),80)||'POR VERIFICAR';
  return{covenin,covenin_verificado:covenin!=='POR VERIFICAR'&&Boolean(first(raw,['covenin_verificado','verified'],false)),criterio_covenin:text(first(raw,['criterio_covenin','criterio_normativo','normative_criterion'],''),2000),unidad:normalizeUnit(first(raw,['unidad','unit'],'und')),cantidad:number(first(raw,['cantidad','computo','quantity'],0)),rendimiento:number(first(raw,['rendimiento','rdto','performance'],0)),fcas:clamp(first(raw,['fcas','fcas_porcentaje','fc_ar'],DEFAULT_CONFIG.defaultFcasPct),0,1000),descripcion_tecnica:text(first(raw,['descripcion_tecnica','descripcion','description'],''),8000)||text(prompt,8000),memoria_calculo:text(first(raw,['memoria_calculo','memoria','calculation_memory'],''),8000),justificacion_rendimiento:text(first(raw,['justificacion_rendimiento','rendimiento_justificacion','performance_justification'],''),5000),criterio_ejecucion:text(first(raw,['criterio_ejecucion','metodo_ejecucion','execution_criterion'],''),5000),supuestos:list(first(raw,['supuestos','assumptions'],[]),20),exclusiones:list(first(raw,['exclusiones','exclusions'],[]),20),advertencias:[...new Set(warnings)].slice(0,20),materiales,equipos,mo};
}

export function normalizeConfig(input={}){return{currency:text(input.currency||DEFAULT_CONFIG.currency,8).toUpperCase()||'USD',locale:text(input.locale||DEFAULT_CONFIG.locale,20)||'es-VE',workdayHours:clamp(input.workdayHours??DEFAULT_CONFIG.workdayHours,1,24),administrationPct:clamp(input.administrationPct??DEFAULT_CONFIG.administrationPct,0,200),contingencyPct:clamp(input.contingencyPct??DEFAULT_CONFIG.contingencyPct,0,200),profitPct:clamp(input.profitPct??DEFAULT_CONFIG.profitPct,0,500),financingPct:clamp(input.financingPct??DEFAULT_CONFIG.financingPct,0,500),taxPct:clamp(input.taxPct??DEFAULT_CONFIG.taxPct,0,100),clientFactor:clamp(input.clientFactor??DEFAULT_CONFIG.clientFactor,.01,100),defaultFcasPct:clamp(input.defaultFcasPct??DEFAULT_CONFIG.defaultFcasPct,0,1000),maxPriceAgeDays:clamp(input.maxPriceAgeDays??DEFAULT_CONFIG.maxPriceAgeDays,1,3650),requireVerifiedPricesForApproval:input.requireVerifiedPricesForApproval!==false}}

export function calculateApu(apu,configInput={}){
  const config=normalizeConfig(configInput),rendimiento=number(apu?.rendimiento,0),safeRend=rendimiento>0?rendimiento:1,fcasRate=clamp(apu?.fcas??config.defaultFcasPct,0,1000)/100;
  const materials=(apu?.materiales||[]).reduce((s,r)=>s+Math.max(0,number(r.cant))*Math.max(0,number(r.precio)),0);
  const equipment=(apu?.equipos||[]).reduce((s,r)=>s+Math.max(0,number(r.cant))*Math.max(0,number(r.tarifa))/safeRend,0);
  const laborDirect=(apu?.mo||[]).reduce((s,r)=>s+Math.max(0,number(r.cant))*Math.max(0,number(r.jornal))/safeRend,0),laborBenefits=laborDirect*fcasRate,labor=laborDirect+laborBenefits,direct=materials+equipment+labor;
  const administration=direct*config.administrationPct/100,contingency=direct*config.contingencyPct/100,profit=direct*config.profitPct/100,financing=direct*config.financingPct/100,indirect=administration+contingency+profit+financing,unitBase=direct+indirect,unitContract=unitBase*config.clientFactor,quantity=Math.max(0,number(apu?.cantidad,0)),subtotal=unitContract*quantity,tax=subtotal*config.taxPct/100,total=subtotal+tax;
  return{materials,equipment,laborDirect,laborBenefits,labor,direct,administration,contingency,profit,financing,indirect,unitBase,unitContract,quantity,subtotal,tax,total,config};
}
function validateRows(type,rows,config,stage,now){const errors=[],warnings=[];rows.forEach((row,index)=>{const label=type==='material'?row.desc:type==='equipo'?row.desc:row.cargo,price=type==='material'?row.precio:type==='equipo'?row.tarifa:row.jornal;if(!text(label,250))errors.push(`${type} ${index+1}: falta descripción.`);if(!(number(row.cant)>0))errors.push(`${label||type}: la cantidad debe ser mayor que cero.`);if(number(price)<0)errors.push(`${label||type}: el precio no puede ser negativo.`);if(!(number(price)>0)){const m=`${label||type}: precio o tarifa igual a cero.`;stage==='approve'?errors.push(m):warnings.push(m)}if(!text(row.fuente_precio,300))warnings.push(`${label||type}: falta fuente del precio.`);if(!row.precio_verificado){const m=`${label||type}: precio no verificado.`;stage==='approve'&&config.requireVerifiedPricesForApproval?errors.push(m):warnings.push(m)}const age=daysOld(row.fecha_precio,now);if(!Number.isFinite(age))warnings.push(`${label||type}: falta fecha del precio.`);else if(age>config.maxPriceAgeDays)warnings.push(`${label||type}: precio con ${age} días de antigüedad.`)});return{errors,warnings}}
export function validateApu(apu,configInput={},options={}){
  const config=normalizeConfig(configInput),stage=options.stage==='approve'?'approve':'draft',now=options.now instanceof Date?options.now:new Date(),errors=[],warnings=[];
  if(!text(apu?.descripcion_tecnica,8000))errors.push('La descripción técnica está vacía.');if(!text(apu?.unidad,30))errors.push('La unidad está vacía.');if(!(number(apu?.cantidad)>0))errors.push('La cantidad total debe ser mayor que cero.');if(!(number(apu?.rendimiento)>0))errors.push('El rendimiento diario debe ser mayor que cero.');if(!(number(apu?.fcas)>=0))errors.push('El FCAS no es válido.');if(!text(apu?.memoria_calculo,8000))warnings.push('Falta memoria de cálculo.');if(!text(apu?.justificacion_rendimiento,5000))warnings.push('Falta justificación del rendimiento.');if(!apu?.covenin_verificado)warnings.push('Código o criterio COVENIN pendiente de verificación documental.');
  const groups=[['material',Array.isArray(apu?.materiales)?apu.materiales:[]],['equipo',Array.isArray(apu?.equipos)?apu.equipos:[]],['mano de obra',Array.isArray(apu?.mo)?apu.mo:[]]];if(groups.reduce((s,g)=>s+g[1].length,0)===0)errors.push('La partida no contiene recursos.');for(const[g,rows]of groups){const v=validateRows(g,rows,config,stage,now);errors.push(...v.errors);warnings.push(...v.warnings)}const calculation=calculateApu(apu,config);if(!(calculation.direct>0)){const m='El costo directo es igual a cero.';stage==='approve'?errors.push(m):warnings.push(m)}if(calculation.unitContract>1e12)errors.push('El precio unitario excede un límite razonable y debe revisarse.');const uniqueErrors=[...new Set(errors)].slice(0,50),uniqueWarnings=[...new Set([...(apu?.advertencias||[]),...warnings])].slice(0,50);return{valid:uniqueErrors.length===0,approvable:stage==='approve'&&uniqueErrors.length===0,errors:uniqueErrors,warnings:uniqueWarnings,score:Math.max(0,Math.round(100-uniqueErrors.length*18-uniqueWarnings.length*3)),calculation};
}
export function applyCatalog(apu,catalog=[]){const index=new Map((Array.isArray(catalog)?catalog:[]).map(item=>[catalogKey(item.type,item.desc,item.und),item])),clone=structuredClone(apu);const apply=(type,rows,field,unit='')=>rows.forEach(row=>{const item=index.get(catalogKey(type,row.desc||row.cargo,unit?row[unit]:''));if(item){row[field]=Math.max(0,number(item.precio));row.fuente_precio=text(item.fuente,300);row.fecha_precio=isoDate(item.fecha);row.precio_verificado=Boolean(item.verificado)}});apply('material',clone.materiales||[],'precio','und');apply('equipo',clone.equipos||[],'tarifa');apply('mano_obra',clone.mo||[],'jornal');return clone}
export function stableHash(value){const input=typeof value==='string'?value:JSON.stringify(value);let hash=2166136261;for(let i=0;i<input.length;i++){hash^=input.charCodeAt(i);hash=Math.imul(hash,16777619)}return`SEI-${(hash>>>0).toString(16).padStart(8,'0').toUpperCase()}`}
export function newProject(){const now=new Date().toISOString();return{schemaVersion:PROJECT_SCHEMA_VERSION,appVersion:APP_VERSION,id:`project-${Date.now()}-${Math.random().toString(16).slice(2)}`,general:{code:'',revision:'0',status:'BORRADOR',obra:'',cliente:'',ubicacion:'',fecha:isoDate(),validityDays:15,paymentTerms:'',currency:'USD',notes:''},config:{...DEFAULT_CONFIG},catalog:[],items:[],logo:'',auditTrail:[{at:now,action:'PROJECT_CREATED',by:'Sistema',detail:APP_VERSION}],createdAt:now,updatedAt:now}}
export function migrateProject(input){if(!input||typeof input!=='object')throw new Error('Proyecto inválido.');if(input.schemaVersion===PROJECT_SCHEMA_VERSION)return{...newProject(),...structuredClone(input),schemaVersion:PROJECT_SCHEMA_VERSION,appVersion:APP_VERSION,config:normalizeConfig(input.config||{}),catalog:Array.isArray(input.catalog)?input.catalog:[],items:Array.isArray(input.items)?input.items:[],auditTrail:Array.isArray(input.auditTrail)?input.auditTrail:[]};const migrated=newProject();migrated.general={...migrated.general,...(input.general||{})};migrated.logo=input.logo||'';migrated.items=Array.isArray(input.items||input.partidas)?structuredClone(input.items||input.partidas):[];migrated.auditTrail.push({at:new Date().toISOString(),action:'PROJECT_MIGRATED',by:'Sistema',detail:`Desde esquema ${input.version||input.schemaVersion||'legacy'}`});return migrated}
