const DOCS=[['01','Control documental','Índice de entrega','Relación de documentos, revisiones y páginas.','00_Indice_de_Entrega_Documental.pdf'],['02','Resumen ejecutivo','Dossier ejecutivo','Alcance, inversión, plazo, riesgos y ruta de aprobación.','01_Dossier_Ejecutivo_SEINCA_Onix_512.pdf'],['03','Documento económico','Presupuesto, APU y cómputos métricos','48 partidas, análisis unitarios y trazabilidad de cantidades.','02_Presupuesto_APU_y_Computos_Metricos_SEINCA_Onix_512.pdf'],['04','Documento técnico','Memoria descriptiva e informe técnico','Justificación integral del alcance, metodología y monto.','03_Memoria_Descriptiva_e_Informe_Tecnico_SEINCA_Onix_512.pdf'],['05','Anexo técnico','Cómputos métricos','Fórmulas, mediciones y niveles de certeza por partida.','04_Anexo_Computos_Metricos_SEINCA_Onix_512.pdf'],['06','Control de acabados','Aprobación de acabados','Porcelanato, revestimientos, pinturas, luminarias y paisajismo.','05_Ficha_Seleccion_y_Aprobacion_de_Acabados.pdf'],['07','Control contractual','Acta de aceptación','Documento para formalizar la aceptación de la propuesta.','06_Acta_de_Aceptacion_Propuesta_SEINCA_Onix_512.pdf']];
const PLANS=[['P00','Presentación del proyecto','render','P00_Presentacion_Proyecto_Onix_512_SEINCA.pdf'],['P01','Planta general','planta','P01_Planta_General_Onix_512_SEINCA.pdf'],['P02','Planta de techo','techo','P02_Planta_Techo_Onix_512_SEINCA.pdf'],['P03','Replanteo, piso y luminarias','planta','P03_Replanteo_Piso_Luminarias_Onix_512_SEINCA.pdf'],['P04','Cortes A-A y B-B','planta','P04_Cortes_AA_BB_Onix_512_SEINCA.pdf'],['P05','Revestimientos','render','P05_Revestimientos_Onix_512_SEINCA.pdf']];
const captions=['En SEINCA entendemos que una buena obra comienza mucho antes de la construcción.','Una propuesta integral para transformar el área exterior en un espacio contemporáneo, funcional y cuidadosamente ejecutado.','El proyecto reúne diseño arquitectónico, ingeniería, planificación y control técnico.','El presupuesto se organiza en cuarenta y ocho partidas, respaldadas por APU y cómputos métricos.','La ejecución se planifica en un plazo estimado de diez a doce semanas.','SEINCA aporta ingeniería, control y calidad para llevar este proyecto del concepto a la realidad.'];
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const EMBEDDED=window.SEINCA_ASSETS||{};
const ASSETS={render:EMBEDDED.render||'',planta:EMBEDDED.planta||'',techo:EMBEDDED.techo||''};
function buildCards(){const dg=$('#doc-grid'),pg=$('#plan-grid');dg.innerHTML=DOCS.map(d=>`<article class="doc-card reveal"><span class="doc-no">${d[0]}</span><small>${d[1]}</small><h3>${d[2]}</h3><p>${d[3]}</p><div class="doc-actions"><a href="/onix-512/documents/${d[4]}" target="_blank" rel="noopener">Abrir ↗</a><a href="/onix-512/documents/${d[4]}" download>Descargar ↓</a></div></article>`).join('');pg.innerHTML=PLANS.map(p=>`<article class="plan-card reveal"><img data-asset="${p[2]}" alt="Vista previa: ${p[1]}" loading="lazy"><div><small>${p[0]}</small><h3>${p[1]}</h3><a href="/onix-512/documents/${p[3]}" target="_blank" rel="noopener">Abrir plano ↗</a> · <a href="/onix-512/documents/${p[3]}" download>Descargar ↓</a></div></article>`).join('')}
function hydrateAssets(){const missing=[];$$('img[data-asset]').forEach(img=>{const key=img.dataset.asset;const source=ASSETS[key];if(source){img.src=source}else{img.classList.add('asset-error');missing.push(key)}});if(missing.length)console.error('Recursos embebidos no disponibles:',[...new Set(missing)])}
function initReveal(){const els=$$('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('in'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');o.unobserve(e.target)}}),{threshold:.1});els.forEach(e=>o.observe(e))}
function initNav(){const menu=$('#menu'),nav=$('#nav');menu.addEventListener('click',()=>nav.classList.toggle('open'));$$('#nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));const sections=$$('main section[id]');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)$$('#nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>io.observe(s))}
function initLightbox(){const m=$('#lightbox'),img=$('#lightbox-img'),cap=$('#lightbox-caption');$$('[data-lightbox-key]').forEach(b=>b.addEventListener('click',()=>{const source=ASSETS[b.dataset.lightboxKey];if(!source){showToast('La vista no está disponible.');return}img.src=source;img.alt=b.dataset.caption||'';cap.textContent=b.dataset.caption||'';m.hidden=false;document.body.style.overflow='hidden'}));const close=()=>{m.hidden=true;document.body.style.overflow=''};$('[data-close]').addEventListener('click',close);m.addEventListener('click',e=>{if(e.target===m)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.hidden)close()})}
function initPresentation(){const modal=$('#presentation'),scenes=$$('.scene',modal),play=$('#play-pause'),bar=$('#progress'),time=$('#time'),caption=$('#caption'),capBtn=$('#captions-toggle');let t=0,running=false,timer=null,caps=true;const duration=72;const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;const update=()=>{const idx=Math.min(scenes.length-1,Math.floor(t/12));scenes.forEach((s,i)=>s.classList.toggle('active',i===idx));bar.style.width=`${t/duration*100}%`;time.textContent=`${fmt(t)} / ${fmt(duration)}`;caption.textContent=caps?captions[idx]:''};const stop=()=>{clearInterval(timer);timer=null;running=false;play.textContent='Reproducir'};const start=()=>{if(running)return;running=true;play.textContent='Pausar';timer=setInterval(()=>{t+=.1;if(t>=duration){t=duration;update();stop();return}update()},100)};const open=()=>{modal.hidden=false;document.body.style.overflow='hidden';t=0;update();start()};const close=()=>{stop();t=0;modal.hidden=true;document.body.style.overflow=''};$$('[data-presentation]').forEach(b=>b.addEventListener('click',open));$('[data-close-presentation]').addEventListener('click',close);play.addEventListener('click',()=>running?stop():start());capBtn.addEventListener('click',()=>{caps=!caps;capBtn.setAttribute('aria-pressed',String(caps));caption.hidden=!caps;update()});$('.progress').addEventListener('click',e=>{const r=e.currentTarget.getBoundingClientRect();t=Math.max(0,Math.min(duration,(e.clientX-r.left)/r.width*duration));update()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close();if(e.code==='Space'&&!modal.hidden){e.preventDefault();play.click()}})}
function validateAssets(){$$('img').forEach(i=>i.addEventListener('error',()=>{i.classList.add('asset-error');console.error('Recurso no disponible:',i.currentSrc||i.src)}))}
function initDownloads(){$$('a[download]').forEach(a=>a.addEventListener('click',()=>showToast('Descarga iniciada.')))}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
buildCards();hydrateAssets();initReveal();initNav();initLightbox();initPresentation();validateAssets();initDownloads();