const DOCS=[
['01','Control documental','Índice de entrega','Relación de documentos, revisiones y páginas.','documents/00_Indice_de_Entrega_Documental.pdf'],
['02','Resumen ejecutivo','Dossier ejecutivo','Alcance, inversión, plazo, riesgos y ruta de aprobación.','documents/01_Dossier_Ejecutivo_SEINCA_Onix_512.pdf'],
['03','Documento económico','Presupuesto, APU y cómputos métricos','48 partidas, análisis unitarios y trazabilidad de cantidades.','documents/02_Presupuesto_APU_y_Computos_Metricos_SEINCA_Onix_512.pdf'],
['04','Documento técnico','Memoria descriptiva e informe técnico','Justificación integral del alcance, metodología y monto.','documents/03_Memoria_Descriptiva_e_Informe_Tecnico_SEINCA_Onix_512.pdf'],
['05','Anexo técnico','Cómputos métricos','Fórmulas, mediciones y niveles de certeza por partida.','documents/04_Anexo_Computos_Metricos_SEINCA_Onix_512.pdf'],
['06','Control de acabados','Aprobación de acabados','Porcelanato, revestimientos, pinturas, luminarias y paisajismo.','documents/05_Ficha_Seleccion_y_Aprobacion_de_Acabados.pdf'],
['07','Control contractual','Acta de aceptación','Documento para formalizar la aceptación de la propuesta.','documents/06_Acta_de_Aceptacion_Propuesta_SEINCA_Onix_512.pdf']
];
const PLANS=[
['P00','Presentación del proyecto','assets/hero.webp','documents/P00_Presentacion_Proyecto_Onix_512_SEINCA.pdf'],
['P01','Planta general','assets/planta.webp','documents/P01_Planta_General_Onix_512_SEINCA.pdf'],
['P02','Planta de techo','assets/techo.webp','documents/P02_Planta_Techo_Onix_512_SEINCA.pdf'],
['P03','Replanteo, piso y luminarias','assets/luces.webp','documents/P03_Replanteo_Piso_Luminarias_Onix_512_SEINCA.pdf'],
['P04','Cortes A-A y B-B','assets/planta.webp','documents/P04_Cortes_AA_BB_Onix_512_SEINCA.pdf'],
['P05','Revestimientos','assets/render.webp','documents/P05_Revestimientos_Onix_512_SEINCA.pdf']
];
const captions=[
[0,16,'En SEINCA entendemos que una buena obra comienza mucho antes de la construcción. Hoy presentamos Onix quinientos doce.'],
[16,34,'Una propuesta integral para transformar el área exterior de la residencia en un espacio contemporáneo, funcional y cuidadosamente ejecutado.'],
[34,54,'El proyecto reúne diseño arquitectónico, ingeniería, planificación y control técnico. Cada elemento se integra en una solución coherente.'],
[54,77,'El presupuesto está organizado en cuarenta y ocho partidas, respaldadas por análisis de precios unitarios y cómputos métricos trazables.'],
[77,98,'La ejecución se planifica en un plazo estimado de diez a doce semanas, desde la validación inicial hasta las pruebas y la entrega.'],
[98,117,'Antes de iniciar se deben cerrar acabados, medidas reales, ingeniería de detalle, equipos y condiciones comerciales.'],
[117,132,'La inversión total es de cuarenta y cinco mil novecientos diecisiete dólares con ocho centavos, IVA incluido.'],
[132,180,'SEINCA aporta ingeniería, control y calidad para llevar este proyecto del concepto a la realidad.']
];
const sceneStarts=[0,22,48,75,101,126];
const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
function buildCards(){const dg=$('#doc-grid');dg.innerHTML=DOCS.map(d=>`<article class="doc-card reveal"><span class="doc-no">${d[0]}</span><small>${d[1]}</small><h3>${d[2]}</h3><p>${d[3]}</p><div class="doc-actions"><a href="${d[4]}" target="_blank" rel="noopener">Abrir ↗</a><a href="${d[4]}" download>Descargar ↓</a></div></article>`).join('');const pg=$('#plan-grid');pg.innerHTML=PLANS.map(p=>`<article class="plan-card reveal"><img src="${p[2]}" alt="Vista previa: ${p[1]}" loading="lazy"><div><small>${p[0]}</small><h3>${p[1]}</h3><a href="${p[3]}" target="_blank" rel="noopener">Abrir plano ↗</a> · <a href="${p[3]}" download>Descargar ↓</a></div></article>`).join('')}
function initReveal(){const els=$$('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('in'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');o.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>o.observe(e))}
function initNav(){const menu=$('#menu'),nav=$('#nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));const ids=$$('main section[id]');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('#nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}}),{rootMargin:'-35% 0px -55%'});ids.forEach(s=>io.observe(s))}
function initLightbox(){const m=$('#lightbox'),img=$('#lightbox-img'),cap=$('#lightbox-caption');$$('[data-lightbox]').forEach(b=>b.addEventListener('click',()=>{img.src=b.dataset.lightbox;img.alt=b.dataset.caption||'';cap.textContent=b.dataset.caption||'';m.hidden=false;document.body.style.overflow='hidden'}));const close=()=>{m.hidden=true;document.body.style.overflow=''};$('[data-close]',m).addEventListener('click',close);m.addEventListener('click',e=>{if(e.target===m)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.hidden)close()})}
function fmt(s){if(!Number.isFinite(s))return'0:00';return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function initPresentation(){const modal=$('#presentation'),audio=$('#narration'),loading=$('#audio-loading'),play=$('#play-pause'),bar=$('#progress'),time=$('#time'),caption=$('#caption'),capBtn=$('#captions-toggle'),scenes=$$('.scene',modal),download=$('.video-download');audio.innerHTML='<source src="/api/voice-sample?full=1" type="audio/mpeg">';audio.load();if(download){download.href='/api/voice-sample?full=1';download.textContent='Narración MP3 ↓';download.removeAttribute('download')}let caps=true;const close=()=>{audio.pause();audio.currentTime=0;modal.hidden=true;document.body.style.overflow='';loading.hidden=false};const showScene=t=>{let idx=0;sceneStarts.forEach((s,i)=>{if(t>=s)idx=i});scenes.forEach((s,i)=>s.classList.toggle('active',i===idx))};const update=()=>{const d=audio.duration||165,t=audio.currentTime;bar.style.width=`${Math.min(100,t/d*100)}%`;time.textContent=`${fmt(t)} / ${fmt(d)}`;showScene(t);const c=captions.find(x=>t>=x[0]&&t<x[1]);caption.textContent=caps&&c?c[2]:''};const start=async()=>{modal.hidden=false;document.body.style.overflow='hidden';loading.hidden=false;loading.textContent='Preparando narración…';audio.currentTime=0;try{await audio.play();loading.hidden=true;play.textContent='Pausar'}catch(err){loading.textContent='Presiona Reproducir para iniciar la narración.';play.textContent='Reproducir'}};$$('[data-presentation]').forEach(b=>b.addEventListener('click',start));$('[data-close-presentation]').addEventListener('click',close);play.addEventListener('click',async()=>{if(audio.paused){await audio.play();play.textContent='Pausar';loading.hidden=true}else{audio.pause();play.textContent='Reproducir'}});audio.addEventListener('timeupdate',update);audio.addEventListener('loadedmetadata',update);audio.addEventListener('playing',()=>loading.hidden=true);audio.addEventListener('waiting',()=>{loading.hidden=false;loading.textContent='Cargando narración natural…'});audio.addEventListener('ended',()=>{play.textContent='Reproducir';showScene(0)});audio.addEventListener('error',()=>{loading.hidden=false;loading.textContent='No fue posible cargar la narración. Recarga la página e inténtalo nuevamente.'});capBtn.addEventListener('click',()=>{caps=!caps;capBtn.setAttribute('aria-pressed',String(caps));caption.hidden=!caps;update()});$('.progress').addEventListener('click',e=>{if(audio.duration){const r=e.currentTarget.getBoundingClientRect();audio.currentTime=(e.clientX-r.left)/r.width*audio.duration}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close();if(e.code==='Space'&&!modal.hidden){e.preventDefault();play.click()}})}
function validateAssets(){$$('img').forEach(i=>i.addEventListener('error',()=>{if(i.id==='lightbox-img'&&!i.src)return;i.classList.add('asset-error');console.error('Recurso no disponible:',i.src)}))}
buildCards();initReveal();initNav();initLightbox();initPresentation();validateAssets();